---
title: "ESM 244 Lab 2"
author: "Jennifer Truong"
date: "1/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set

library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

# For PCA
library(ggfortify)

# For ggplot customization
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# To make compound figures:
library(patchwork)
```

## Part 1: PCA with Penguins

```{r}
penguin_pca <- penguins %>%
  select(body_mass_g, ends_with("_mm")) %>%
  drop_na() %>% # Drop NA in all variables
  scale() %>% # Scale all variables to give equal weight
  prcomp() # Run PCA

penguin_pca$rotation # PCA Loadings

penguin_complete <- penguins %>%
  drop_na(body_mass_g, ends_with("_mm")) # Drop NA from only these variables

# Create bi-plot ----

autoplot(penguin_pca,
         data = penguin_complete,
         colour = 'species',
         loadings = TRUE, # Show PCA loadings
         loadings.label = TRUE) + # Label PCA loadings
  theme_minimal()
```

### Part 2: ggplot2 customization & reading in different file types

#### Read in an .xlsx file & do some wrangling

```{r}

fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>%
  clean_names() %>%
  mutate(across(where(is.character), tolower)) %>% # Change to lower case across columns that are character class
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>% # Transform nmfs_name to remove last four characters in string
  filter(confidentiality == "public") # Keep only rows that are public

```

Make a customized graph:

```{r}
fish_plot <- ggplot(data = fish_noaa, 
                    aes(x = year, y = pounds)) +
  geom_line(aes(color = nmfs_name),
            show.legend = FALSE) +
  theme_minimal()

ggplotly(fish_plot) # Interactive plot

ggplot(data = fish_noaa, 
       aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  theme_minimal() +
  gghighlight(max(pounds) > 1e8)
```

#### Read in data from a URL, `lubridate()`, `mutate()`, make a graph with months in logical order

```{r}
monroe_wt <- read_csv("https://data.bloomington.in.gov/dataset/2c81cfe3-62c2-46ed-8fcf-83c1880301d1/resource/13c8f7aa-af51-4008-80a9-56415c7c931e/download/mwtpdailyelectricitybclear.csv") %>%
  clean_names()
```
```{r}
monroe_ts <- monroe_wt %>%
  mutate(date = mdy(date)) %>%
  mutate(record_month = month(date)) %>%
  mutate(month_name = month.abb[record_month]) %>%
  mutate(month_name = fct_reorder(month_name, record_month))

ggplot(data = monroe_ts, 
       aes(x = month_name, y = total_k_wh)) +
  geom_jitter()
```

### Part 3: Compound figures with `patchwork`

```{r}

graph_a <- ggplot(data = penguins,
                  aes(x = body_mass_g, y = flipper_length_mm)) +
  geom_point()

graph_b <- ggplot(data = penguins,
                  aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species),
              show.legend = FALSE)

# Use | to put graphs side by side
# Use / to put graphs one over the other

graph_c <- (graph_a | graph_b) / fish_plot & theme_dark()

graph_c

```

